language: node_js
node_js:
  - '12'
  - '10'
  - '8'
after_success: npm run coveralls
stages:
  - test
  - name: npm release
    if: tag IS present
jobs:
  include:
    - stage: npm release
      install: skip
      script: skip
      after_success: true # skip step with success exit code
      deploy:
        provider: npm
        email: nwoltman@outlook.com
        on:
          tags: true
        api_key:
          secure: pjEt0+e3c04nMiwSH1P1/kkKp/NShhwFFVN8EzX/hBoJhFwqxlioSZbWGizJPlU05UcF/ipRLIaxqe6rDhBXz0MzECb7ZWy71LpijbtxwGebDk/HeX5cN+8uWk16eUFAXXsjk9cEKI6eel3OWiQ/y233PufJa2u4InuEGWBc+qr5lP4BgbYfZCdhi43uhW6NnQSz96yPtTAZ1lQXb+mT6RTl4bBRLn9qoXyXtNwgenHvZtf2KcQfFFILP5BORDjUnBSrJ4Mu6p2H7oDWJxW4NCTJi7JGysSTCQTUORV1prGvvwdSBezeXYYRcCEQZIj3xAmT+PhqNiWsSuxBaiwUoLRL+2opaofziY8l+H9sabeLs+u0L8cVN6QKHr+Ivout0+9hgG2VpNnUYPPjw8lfsCEeBdaQzq/PMdr1MyQ8Q5XE8j5DVVTMxjbVBrUVraGSRHy8gWTDPapsz/Xv5fveE/A9zl0pxORmXb4Nhfpfcb2slFb8qBI3E5t5xTCWjG5lG+Bd4OU+v91MXWndZvzncZkPrjtQmtSUA7uIX2F32V3AreKvXWkXj0z8ob1D4LILc0SwmQD3jsXnw/hQcNyUX2NSPOWoA8lP7bXUh2IrduDIp+qVcxrsYj1eW8W5BmdKUkmQZCDJHWBnGUT0I1ZrbycnOkw7Lw3SyyoUpr2SlRk=
